import type { Metadata } from 'next';
import {
	Inter as FontSans,
	Playfair_Display as FontSerif,
	JetBrains_Mono as FontMono,
} from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans',
});

const fontSerif = FontSerif({
	subsets: ['latin'],
	variable: '--font-serif',
});

const fontMono = FontMono({
	subsets: ['latin'],
	variable: '--font-mono',
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased',
					fontSans.variable,
					fontSerif.variable,
					fontMono.variable,
				)}
			>
				{children}
			</body>
		</html>
	);
}
